{{- range $name, $app := $.Values.app }}
{{- if hasKey $app "cron" }}
{{- range $app.cron.tasks }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $name }}-{{.name | lower}}"
  annotations:
    owner: {{.owner | default $.Values.cron.defaultOwner}}
  {{- if .description }}
    description: {{ .description | quote }}
  {{- end}}
spec:
  schedule: {{.schedule | quote}}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      activeDeadlineSeconds: {{ .timeout | default $.Values.cron.defaultTimeout}}
      backoffLimit: 1
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: "task-{{ $name }}-{{.name | lower}}"
            image: "{{ $.Values.image.repo }}"
            command: ["node", "dist/taskRunner/index.js", {{.name | quote}}]
            imagePullPolicy: IfNotPresent
            resources:
              {{- toYaml $app.resources | nindent 14 }}
            envFrom:
            - configMapRef:
                name: {{ $name }}-configmap
            - secretRef:
                name: {{ $name }}-secrets
          restartPolicy: OnFailure
---
{{- end }}
{{- end }}
{{- end }}
